CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS sys_campus (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(100) NOT NULL,
  short_name VARCHAR(50),
  contact_name VARCHAR(50),
  contact_phone VARCHAR(20),
  address VARCHAR(255),
  latitude NUMERIC(10, 6),
  longitude NUMERIC(10, 6),
  business_hours VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
  settings JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0
);
COMMENT ON TABLE sys_campus IS '校区基础信息';
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_campus_code_alive ON sys_campus (code) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  real_name VARCHAR(50) NOT NULL,
  phone VARCHAR(20),
  email VARCHAR(120),
  avatar_url VARCHAR(512),
  account_type VARCHAR(32) NOT NULL,
  wx_open_id VARCHAR(128),
  wx_union_id VARCHAR(128),
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
  last_login_at TIMESTAMPTZ,
  last_login_ip VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0
);
COMMENT ON TABLE sys_user IS '系统登录用户，覆盖后台、老师端和家长端账号';
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_username_alive ON sys_user (username) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_sys_user_phone ON sys_user (phone);
CREATE INDEX IF NOT EXISTS idx_sys_user_wx_open_id ON sys_user (wx_open_id);

CREATE TABLE IF NOT EXISTS sys_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT REFERENCES sys_campus (id),
  code VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  scope_type VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
  data_scope VARCHAR(20) NOT NULL DEFAULT 'CAMPUS',
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
  remark VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0
);
COMMENT ON TABLE sys_role IS 'RBAC角色';
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_role_scope_code_alive
  ON sys_role (COALESCE(campus_id, 0), code) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS sys_permission (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT REFERENCES sys_permission (id),
  code VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  permission_type VARCHAR(20) NOT NULL,
  route_path VARCHAR(255),
  component VARCHAR(255),
  api_method VARCHAR(16),
  api_path VARCHAR(255),
  icon VARCHAR(64),
  sort_order INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0
);
COMMENT ON TABLE sys_permission IS 'RBAC权限点';
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_permission_code_alive ON sys_permission (code) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_sys_permission_parent ON sys_permission (parent_id);

CREATE TABLE IF NOT EXISTS sys_role_permission (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id BIGINT NOT NULL REFERENCES sys_role (id),
  permission_id BIGINT NOT NULL REFERENCES sys_permission (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0
);
COMMENT ON TABLE sys_role_permission IS '角色权限关系';
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_role_permission_alive
  ON sys_role_permission (role_id, permission_id) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS sys_user_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES sys_user (id),
  role_id BIGINT NOT NULL REFERENCES sys_role (id),
  campus_id BIGINT REFERENCES sys_campus (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0
);
COMMENT ON TABLE sys_user_role IS '用户角色关系，可按校区授权';
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_role_alive
  ON sys_user_role (user_id, role_id, COALESCE(campus_id, 0)) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS sys_user_campus (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES sys_user (id),
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  relation_type VARCHAR(20) NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0
);
COMMENT ON TABLE sys_user_campus IS '用户可访问校区范围';
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_campus_alive
  ON sys_user_campus (user_id, campus_id, relation_type) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS edu_teacher (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  user_id BIGINT REFERENCES sys_user (id),
  employee_no VARCHAR(32) NOT NULL,
  name VARCHAR(50) NOT NULL,
  gender VARCHAR(10),
  phone VARCHAR(20),
  title VARCHAR(50),
  specialties JSONB NOT NULL DEFAULT '[]'::JSONB,
  intro TEXT,
  hire_date DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_edu_teacher_campus_id_id UNIQUE (campus_id, id)
);
COMMENT ON TABLE edu_teacher IS '老师档案';
CREATE UNIQUE INDEX IF NOT EXISTS uk_edu_teacher_employee_no_alive
  ON edu_teacher (campus_id, employee_no) WHERE deleted = 0;
CREATE UNIQUE INDEX IF NOT EXISTS uk_edu_teacher_user_alive
  ON edu_teacher (campus_id, user_id) WHERE user_id IS NOT NULL AND deleted = 0;

CREATE TABLE IF NOT EXISTS edu_course (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  course_code VARCHAR(32) NOT NULL,
  course_system VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  level_name VARCHAR(50),
  target_age_min NUMERIC(4, 1),
  target_age_max NUMERIC(4, 1),
  grade_scope VARCHAR(100),
  total_hours NUMERIC(8, 2) NOT NULL DEFAULT 0,
  unit_price NUMERIC(10, 2) NOT NULL DEFAULT 0,
  package_price NUMERIC(10, 2) NOT NULL DEFAULT 0,
  description TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_edu_course_campus_id_id UNIQUE (campus_id, id)
);
COMMENT ON TABLE edu_course IS '课程体系与售卖课程';
CREATE UNIQUE INDEX IF NOT EXISTS uk_edu_course_code_alive
  ON edu_course (campus_id, course_code) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS edu_class (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  course_id BIGINT NOT NULL,
  class_no VARCHAR(32) NOT NULL,
  name VARCHAR(100) NOT NULL,
  head_teacher_id BIGINT,
  classroom VARCHAR(100),
  class_wechat_qr_url VARCHAR(512),
  start_date DATE,
  end_date DATE,
  max_students INTEGER NOT NULL DEFAULT 8,
  current_students INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'PREPARING',
  remark VARCHAR(500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_edu_class_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_edu_class_course FOREIGN KEY (campus_id, course_id) REFERENCES edu_course (campus_id, id),
  CONSTRAINT fk_edu_class_head_teacher FOREIGN KEY (campus_id, head_teacher_id) REFERENCES edu_teacher (campus_id, id)
);
COMMENT ON TABLE edu_class IS '班级';
CREATE UNIQUE INDEX IF NOT EXISTS uk_edu_class_no_alive
  ON edu_class (campus_id, class_no) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_edu_class_course ON edu_class (campus_id, course_id);

CREATE TABLE IF NOT EXISTS edu_class_teacher (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  class_id BIGINT NOT NULL,
  teacher_id BIGINT NOT NULL,
  role_type VARCHAR(20) NOT NULL DEFAULT 'TEACHER',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_class_teacher_class FOREIGN KEY (campus_id, class_id) REFERENCES edu_class (campus_id, id),
  CONSTRAINT fk_class_teacher_teacher FOREIGN KEY (campus_id, teacher_id) REFERENCES edu_teacher (campus_id, id)
);
COMMENT ON TABLE edu_class_teacher IS '班级任课老师关系';
CREATE UNIQUE INDEX IF NOT EXISTS uk_edu_class_teacher_alive
  ON edu_class_teacher (campus_id, class_id, teacher_id, role_type) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS edu_guardian (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  user_id BIGINT REFERENCES sys_user (id),
  name VARCHAR(50) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  wx_open_id VARCHAR(128),
  wx_union_id VARCHAR(128),
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_edu_guardian_campus_id_id UNIQUE (campus_id, id)
);
COMMENT ON TABLE edu_guardian IS '家长/监护人';
CREATE INDEX IF NOT EXISTS idx_edu_guardian_phone ON edu_guardian (campus_id, phone);
CREATE UNIQUE INDEX IF NOT EXISTS uk_edu_guardian_user_alive
  ON edu_guardian (campus_id, user_id) WHERE user_id IS NOT NULL AND deleted = 0;

CREATE TABLE IF NOT EXISTS edu_student (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  student_no VARCHAR(32) NOT NULL,
  name VARCHAR(50) NOT NULL,
  nickname VARCHAR(50),
  avatar_url VARCHAR(512),
  gender VARCHAR(10),
  birthday DATE,
  grade VARCHAR(30),
  school VARCHAR(100),
  english_level VARCHAR(50),
  learning_goal VARCHAR(255),
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  enrolled_at DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_edu_student_campus_id_id UNIQUE (campus_id, id)
);
COMMENT ON TABLE edu_student IS '学生档案';
CREATE UNIQUE INDEX IF NOT EXISTS uk_edu_student_no_alive
  ON edu_student (campus_id, student_no) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_edu_student_name ON edu_student (campus_id, name);

CREATE TABLE IF NOT EXISTS edu_student_guardian (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  student_id BIGINT NOT NULL,
  guardian_id BIGINT NOT NULL,
  relation VARCHAR(20) NOT NULL,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_student_guardian_student FOREIGN KEY (campus_id, student_id) REFERENCES edu_student (campus_id, id),
  CONSTRAINT fk_student_guardian_guardian FOREIGN KEY (campus_id, guardian_id) REFERENCES edu_guardian (campus_id, id)
);
COMMENT ON TABLE edu_student_guardian IS '学生与监护人关系';
CREATE UNIQUE INDEX IF NOT EXISTS uk_edu_student_guardian_alive
  ON edu_student_guardian (campus_id, student_id, guardian_id) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS edu_class_student (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  class_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  join_date DATE NOT NULL DEFAULT CURRENT_DATE,
  leave_date DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_class_student_class FOREIGN KEY (campus_id, class_id) REFERENCES edu_class (campus_id, id),
  CONSTRAINT fk_class_student_student FOREIGN KEY (campus_id, student_id) REFERENCES edu_student (campus_id, id)
);
COMMENT ON TABLE edu_class_student IS '班级学生关系';
CREATE UNIQUE INDEX IF NOT EXISTS uk_edu_class_student_alive
  ON edu_class_student (campus_id, class_id, student_id) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS edu_class_schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  class_id BIGINT NOT NULL,
  course_id BIGINT NOT NULL,
  teacher_id BIGINT NOT NULL,
  lesson_no INTEGER,
  lesson_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  topic VARCHAR(150) NOT NULL,
  content TEXT,
  lesson_hours NUMERIC(5, 2) NOT NULL DEFAULT 1,
  status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
  classroom VARCHAR(100),
  online_url VARCHAR(512),
  remark VARCHAR(500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_class_schedule_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_class_schedule_class FOREIGN KEY (campus_id, class_id) REFERENCES edu_class (campus_id, id),
  CONSTRAINT fk_class_schedule_course FOREIGN KEY (campus_id, course_id) REFERENCES edu_course (campus_id, id),
  CONSTRAINT fk_class_schedule_teacher FOREIGN KEY (campus_id, teacher_id) REFERENCES edu_teacher (campus_id, id)
);
COMMENT ON TABLE edu_class_schedule IS '班级课表';
CREATE INDEX IF NOT EXISTS idx_class_schedule_date ON edu_class_schedule (campus_id, lesson_date, start_time);
CREATE UNIQUE INDEX IF NOT EXISTS uk_class_schedule_lesson_alive
  ON edu_class_schedule (campus_id, class_id, lesson_no) WHERE lesson_no IS NOT NULL AND deleted = 0;

CREATE TABLE IF NOT EXISTS res_file (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  storage_type VARCHAR(20) NOT NULL DEFAULT 'OSS',
  bucket_name VARCHAR(100),
  object_key VARCHAR(512) NOT NULL,
  url VARCHAR(1024) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  content_type VARCHAR(120),
  file_size BIGINT NOT NULL DEFAULT 0,
  checksum VARCHAR(128),
  uploader_id BIGINT REFERENCES sys_user (id),
  biz_type VARCHAR(50),
  status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_res_file_campus_id_id UNIQUE (campus_id, id)
);
COMMENT ON TABLE res_file IS '统一文件对象';
CREATE INDEX IF NOT EXISTS idx_res_file_biz ON res_file (campus_id, biz_type);

CREATE TABLE IF NOT EXISTS res_category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  parent_id BIGINT,
  category_type VARCHAR(30) NOT NULL DEFAULT 'MATERIAL',
  name VARCHAR(100) NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_res_category_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_res_category_parent FOREIGN KEY (campus_id, parent_id) REFERENCES res_category (campus_id, id)
);
COMMENT ON TABLE res_category IS '资料分类';
CREATE UNIQUE INDEX IF NOT EXISTS uk_res_category_name_alive
  ON res_category (campus_id, COALESCE(parent_id, 0), category_type, name) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS res_material (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  category_id BIGINT NOT NULL,
  title VARCHAR(150) NOT NULL,
  description TEXT,
  resource_type VARCHAR(30) NOT NULL,
  cover_file_id BIGINT,
  file_id BIGINT NOT NULL,
  owner_teacher_id BIGINT,
  visibility VARCHAR(20) NOT NULL DEFAULT 'CAMPUS',
  study_type VARCHAR(20) NOT NULL DEFAULT 'OPTIONAL',
  allow_download BOOLEAN NOT NULL DEFAULT FALSE,
  audit_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  audit_by BIGINT REFERENCES sys_user (id),
  audit_time TIMESTAMPTZ,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_res_material_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_res_material_category FOREIGN KEY (campus_id, category_id) REFERENCES res_category (campus_id, id),
  CONSTRAINT fk_res_material_cover FOREIGN KEY (campus_id, cover_file_id) REFERENCES res_file (campus_id, id),
  CONSTRAINT fk_res_material_file FOREIGN KEY (campus_id, file_id) REFERENCES res_file (campus_id, id),
  CONSTRAINT fk_res_material_teacher FOREIGN KEY (campus_id, owner_teacher_id) REFERENCES edu_teacher (campus_id, id)
);
COMMENT ON TABLE res_material IS '教学资料';
CREATE INDEX IF NOT EXISTS idx_res_material_category ON res_material (campus_id, category_id);
CREATE INDEX IF NOT EXISTS idx_res_material_audit ON res_material (campus_id, audit_status);

CREATE TABLE IF NOT EXISTS res_material_class (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  material_id BIGINT NOT NULL,
  class_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_material_class_material FOREIGN KEY (campus_id, material_id) REFERENCES res_material (campus_id, id),
  CONSTRAINT fk_material_class_class FOREIGN KEY (campus_id, class_id) REFERENCES edu_class (campus_id, id)
);
COMMENT ON TABLE res_material_class IS '资料可见班级';
CREATE UNIQUE INDEX IF NOT EXISTS uk_res_material_class_alive
  ON res_material_class (campus_id, material_id, class_id) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS ops_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  title VARCHAR(150) NOT NULL,
  description TEXT,
  cover_file_id BIGINT,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  location VARCHAR(200) NOT NULL,
  fee NUMERIC(10, 2) NOT NULL DEFAULT 0,
  quota INTEGER,
  registered_count INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_ops_activity_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_ops_activity_cover FOREIGN KEY (campus_id, cover_file_id) REFERENCES res_file (campus_id, id)
);
COMMENT ON TABLE ops_activity IS '校区活动';
CREATE INDEX IF NOT EXISTS idx_ops_activity_time ON ops_activity (campus_id, start_time, status);

CREATE TABLE IF NOT EXISTS fin_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  order_no VARCHAR(40) NOT NULL,
  order_type VARCHAR(20) NOT NULL,
  student_id BIGINT,
  guardian_id BIGINT,
  course_id BIGINT,
  activity_id BIGINT,
  total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  paid_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  pay_status VARCHAR(20) NOT NULL DEFAULT 'UNPAID',
  pay_channel VARCHAR(20),
  transaction_no VARCHAR(80),
  pay_time TIMESTAMPTZ,
  status VARCHAR(20) NOT NULL DEFAULT 'CREATED',
  remark VARCHAR(500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_fin_order_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_fin_order_student FOREIGN KEY (campus_id, student_id) REFERENCES edu_student (campus_id, id),
  CONSTRAINT fk_fin_order_guardian FOREIGN KEY (campus_id, guardian_id) REFERENCES edu_guardian (campus_id, id),
  CONSTRAINT fk_fin_order_course FOREIGN KEY (campus_id, course_id) REFERENCES edu_course (campus_id, id),
  CONSTRAINT fk_fin_order_activity FOREIGN KEY (campus_id, activity_id) REFERENCES ops_activity (campus_id, id)
);
COMMENT ON TABLE fin_order IS '订单主表，覆盖课程购买和活动报名';
CREATE UNIQUE INDEX IF NOT EXISTS uk_fin_order_no_alive ON fin_order (order_no) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_fin_order_student ON fin_order (campus_id, student_id, order_type);
CREATE INDEX IF NOT EXISTS idx_fin_order_pay_status ON fin_order (campus_id, pay_status);

CREATE TABLE IF NOT EXISTS fin_payment_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  order_id BIGINT NOT NULL,
  payment_no VARCHAR(40) NOT NULL,
  pay_channel VARCHAR(20) NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  transaction_no VARCHAR(80),
  status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
  paid_at TIMESTAMPTZ,
  raw_response JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_payment_order FOREIGN KEY (campus_id, order_id) REFERENCES fin_order (campus_id, id)
);
COMMENT ON TABLE fin_payment_record IS '支付流水';
CREATE UNIQUE INDEX IF NOT EXISTS uk_fin_payment_no_alive
  ON fin_payment_record (payment_no) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS ops_activity_registration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  activity_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  guardian_id BIGINT,
  order_id BIGINT,
  registration_no VARCHAR(40) NOT NULL,
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'REGISTERED',
  registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  cancelled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_activity_registration_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_activity_reg_activity FOREIGN KEY (campus_id, activity_id) REFERENCES ops_activity (campus_id, id),
  CONSTRAINT fk_activity_reg_student FOREIGN KEY (campus_id, student_id) REFERENCES edu_student (campus_id, id),
  CONSTRAINT fk_activity_reg_guardian FOREIGN KEY (campus_id, guardian_id) REFERENCES edu_guardian (campus_id, id),
  CONSTRAINT fk_activity_reg_order FOREIGN KEY (campus_id, order_id) REFERENCES fin_order (campus_id, id)
);
COMMENT ON TABLE ops_activity_registration IS '活动报名记录';
CREATE UNIQUE INDEX IF NOT EXISTS uk_activity_registration_no_alive
  ON ops_activity_registration (registration_no) WHERE deleted = 0;
CREATE UNIQUE INDEX IF NOT EXISTS uk_activity_registration_student_alive
  ON ops_activity_registration (campus_id, activity_id, student_id) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS edu_lesson_hour_account (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  student_id BIGINT NOT NULL,
  course_id BIGINT NOT NULL,
  purchased_hours NUMERIC(8, 2) NOT NULL DEFAULT 0,
  gift_hours NUMERIC(8, 2) NOT NULL DEFAULT 0,
  adjusted_hours NUMERIC(8, 2) NOT NULL DEFAULT 0,
  consumed_hours NUMERIC(8, 2) NOT NULL DEFAULT 0,
  refunded_hours NUMERIC(8, 2) NOT NULL DEFAULT 0,
  locked_hours NUMERIC(8, 2) NOT NULL DEFAULT 0,
  remaining_hours NUMERIC(8, 2) GENERATED ALWAYS AS (
    purchased_hours + gift_hours + adjusted_hours - consumed_hours - refunded_hours - locked_hours
  ) STORED,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_lesson_account_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_lesson_account_student FOREIGN KEY (campus_id, student_id) REFERENCES edu_student (campus_id, id),
  CONSTRAINT fk_lesson_account_course FOREIGN KEY (campus_id, course_id) REFERENCES edu_course (campus_id, id)
);
COMMENT ON TABLE edu_lesson_hour_account IS '学生课程课时账户';
CREATE UNIQUE INDEX IF NOT EXISTS uk_lesson_account_student_course_alive
  ON edu_lesson_hour_account (campus_id, student_id, course_id) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS edu_lesson_hour_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  account_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  course_id BIGINT NOT NULL,
  class_id BIGINT,
  schedule_id BIGINT,
  order_id BIGINT,
  change_type VARCHAR(20) NOT NULL,
  hours_delta NUMERIC(8, 2) NOT NULL,
  balance_after NUMERIC(8, 2) NOT NULL,
  operator_id BIGINT REFERENCES sys_user (id),
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  remark VARCHAR(500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_lesson_record_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_lesson_record_account FOREIGN KEY (campus_id, account_id) REFERENCES edu_lesson_hour_account (campus_id, id),
  CONSTRAINT fk_lesson_record_student FOREIGN KEY (campus_id, student_id) REFERENCES edu_student (campus_id, id),
  CONSTRAINT fk_lesson_record_course FOREIGN KEY (campus_id, course_id) REFERENCES edu_course (campus_id, id),
  CONSTRAINT fk_lesson_record_class FOREIGN KEY (campus_id, class_id) REFERENCES edu_class (campus_id, id),
  CONSTRAINT fk_lesson_record_schedule FOREIGN KEY (campus_id, schedule_id) REFERENCES edu_class_schedule (campus_id, id),
  CONSTRAINT fk_lesson_record_order FOREIGN KEY (campus_id, order_id) REFERENCES fin_order (campus_id, id)
);
COMMENT ON TABLE edu_lesson_hour_record IS '课时购买、消耗、调整流水';
CREATE INDEX IF NOT EXISTS idx_lesson_record_student ON edu_lesson_hour_record (campus_id, student_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS edu_attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  schedule_id BIGINT NOT NULL,
  class_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PRESENT',
  check_time TIMESTAMPTZ,
  checked_by BIGINT REFERENCES sys_user (id),
  consumed_hours NUMERIC(5, 2) NOT NULL DEFAULT 0,
  hour_record_id BIGINT,
  remark VARCHAR(500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_attendance_schedule FOREIGN KEY (campus_id, schedule_id) REFERENCES edu_class_schedule (campus_id, id),
  CONSTRAINT fk_attendance_class FOREIGN KEY (campus_id, class_id) REFERENCES edu_class (campus_id, id),
  CONSTRAINT fk_attendance_student FOREIGN KEY (campus_id, student_id) REFERENCES edu_student (campus_id, id),
  CONSTRAINT fk_attendance_hour_record FOREIGN KEY (campus_id, hour_record_id) REFERENCES edu_lesson_hour_record (campus_id, id)
);
COMMENT ON TABLE edu_attendance IS '课堂考勤';
CREATE UNIQUE INDEX IF NOT EXISTS uk_attendance_schedule_student_alive
  ON edu_attendance (campus_id, schedule_id, student_id) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS edu_homework (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  teacher_id BIGINT NOT NULL,
  title VARCHAR(150) NOT NULL,
  content TEXT NOT NULL,
  target_type VARCHAR(20) NOT NULL DEFAULT 'CLASS',
  deadline TIMESTAMPTZ,
  checkin_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  checkin_cycle_days INTEGER,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_homework_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_homework_teacher FOREIGN KEY (campus_id, teacher_id) REFERENCES edu_teacher (campus_id, id)
);
COMMENT ON TABLE edu_homework IS '作业';
CREATE INDEX IF NOT EXISTS idx_homework_teacher_status ON edu_homework (campus_id, teacher_id, status);

CREATE TABLE IF NOT EXISTS edu_homework_target (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  homework_id BIGINT NOT NULL,
  class_id BIGINT,
  student_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_homework_target_homework FOREIGN KEY (campus_id, homework_id) REFERENCES edu_homework (campus_id, id),
  CONSTRAINT fk_homework_target_class FOREIGN KEY (campus_id, class_id) REFERENCES edu_class (campus_id, id),
  CONSTRAINT fk_homework_target_student FOREIGN KEY (campus_id, student_id) REFERENCES edu_student (campus_id, id)
);
COMMENT ON TABLE edu_homework_target IS '作业发布对象';
CREATE INDEX IF NOT EXISTS idx_homework_target_homework ON edu_homework_target (campus_id, homework_id);

CREATE TABLE IF NOT EXISTS edu_homework_attachment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  homework_id BIGINT NOT NULL,
  file_id BIGINT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_homework_attachment_homework FOREIGN KEY (campus_id, homework_id) REFERENCES edu_homework (campus_id, id),
  CONSTRAINT fk_homework_attachment_file FOREIGN KEY (campus_id, file_id) REFERENCES res_file (campus_id, id)
);
COMMENT ON TABLE edu_homework_attachment IS '作业附件';

CREATE TABLE IF NOT EXISTS edu_homework_submission (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  homework_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  content TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED',
  submitted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_homework_submission_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_homework_submission_homework FOREIGN KEY (campus_id, homework_id) REFERENCES edu_homework (campus_id, id),
  CONSTRAINT fk_homework_submission_student FOREIGN KEY (campus_id, student_id) REFERENCES edu_student (campus_id, id)
);
COMMENT ON TABLE edu_homework_submission IS '作业提交';
CREATE UNIQUE INDEX IF NOT EXISTS uk_homework_submission_alive
  ON edu_homework_submission (campus_id, homework_id, student_id) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS edu_homework_submission_file (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  submission_id BIGINT NOT NULL,
  file_id BIGINT NOT NULL,
  media_type VARCHAR(30) NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_submission_file_submission FOREIGN KEY (campus_id, submission_id) REFERENCES edu_homework_submission (campus_id, id),
  CONSTRAINT fk_submission_file_file FOREIGN KEY (campus_id, file_id) REFERENCES res_file (campus_id, id)
);
COMMENT ON TABLE edu_homework_submission_file IS '作业提交附件';

CREATE TABLE IF NOT EXISTS edu_homework_comment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  submission_id BIGINT NOT NULL,
  teacher_id BIGINT NOT NULL,
  comment_text TEXT,
  voice_file_id BIGINT,
  rating INTEGER,
  commented_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_homework_comment_submission FOREIGN KEY (campus_id, submission_id) REFERENCES edu_homework_submission (campus_id, id),
  CONSTRAINT fk_homework_comment_teacher FOREIGN KEY (campus_id, teacher_id) REFERENCES edu_teacher (campus_id, id),
  CONSTRAINT fk_homework_comment_voice FOREIGN KEY (campus_id, voice_file_id) REFERENCES res_file (campus_id, id)
);
COMMENT ON TABLE edu_homework_comment IS '老师作业点评';
CREATE INDEX IF NOT EXISTS idx_homework_comment_submission ON edu_homework_comment (campus_id, submission_id);

CREATE TABLE IF NOT EXISTS edu_homework_checkin (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  homework_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  checkin_date DATE NOT NULL,
  content TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED',
  submitted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_homework_checkin_homework FOREIGN KEY (campus_id, homework_id) REFERENCES edu_homework (campus_id, id),
  CONSTRAINT fk_homework_checkin_student FOREIGN KEY (campus_id, student_id) REFERENCES edu_student (campus_id, id)
);
COMMENT ON TABLE edu_homework_checkin IS '周期打卡作业明细';
CREATE UNIQUE INDEX IF NOT EXISTS uk_homework_checkin_day_alive
  ON edu_homework_checkin (campus_id, homework_id, student_id, checkin_date) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS grp_rule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  min_members INTEGER NOT NULL DEFAULT 4,
  trial_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  auto_fail_days INTEGER NOT NULL DEFAULT 14,
  poster_template_file_id BIGINT,
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_grp_rule_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_grp_rule_poster FOREIGN KEY (campus_id, poster_template_file_id) REFERENCES res_file (campus_id, id)
);
COMMENT ON TABLE grp_rule IS '拼班校区规则';
CREATE UNIQUE INDEX IF NOT EXISTS uk_grp_rule_campus_alive ON grp_rule (campus_id) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS grp_request (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  request_no VARCHAR(40) NOT NULL,
  initiator_student_id BIGINT,
  initiator_guardian_id BIGINT,
  child_age NUMERIC(4, 1),
  grade VARCHAR(30),
  target_system VARCHAR(80),
  english_level VARCHAR(80),
  preferred_times JSONB NOT NULL DEFAULT '[]'::JSONB,
  remark VARCHAR(500),
  required_members INTEGER NOT NULL DEFAULT 4,
  current_members INTEGER NOT NULL DEFAULT 1,
  status VARCHAR(30) NOT NULL DEFAULT 'FORMING',
  share_code VARCHAR(64) NOT NULL,
  poster_file_id BIGINT,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_grp_request_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_grp_request_student FOREIGN KEY (campus_id, initiator_student_id) REFERENCES edu_student (campus_id, id),
  CONSTRAINT fk_grp_request_guardian FOREIGN KEY (campus_id, initiator_guardian_id) REFERENCES edu_guardian (campus_id, id),
  CONSTRAINT fk_grp_request_poster FOREIGN KEY (campus_id, poster_file_id) REFERENCES res_file (campus_id, id)
);
COMMENT ON TABLE grp_request IS '拼班发起单';
CREATE UNIQUE INDEX IF NOT EXISTS uk_grp_request_no_alive ON grp_request (request_no) WHERE deleted = 0;
CREATE UNIQUE INDEX IF NOT EXISTS uk_grp_request_share_code_alive ON grp_request (share_code) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_grp_request_status ON grp_request (campus_id, status);

CREATE TABLE IF NOT EXISTS grp_member (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  request_id BIGINT NOT NULL,
  student_id BIGINT,
  guardian_id BIGINT,
  nickname VARCHAR(80),
  avatar_url VARCHAR(512),
  phone VARCHAR(20),
  join_status VARCHAR(20) NOT NULL DEFAULT 'JOINED',
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  quit_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_grp_member_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_grp_member_request FOREIGN KEY (campus_id, request_id) REFERENCES grp_request (campus_id, id),
  CONSTRAINT fk_grp_member_student FOREIGN KEY (campus_id, student_id) REFERENCES edu_student (campus_id, id),
  CONSTRAINT fk_grp_member_guardian FOREIGN KEY (campus_id, guardian_id) REFERENCES edu_guardian (campus_id, id)
);
COMMENT ON TABLE grp_member IS '拼班成员';
CREATE UNIQUE INDEX IF NOT EXISTS uk_grp_member_student_alive
  ON grp_member (campus_id, request_id, student_id) WHERE student_id IS NOT NULL AND deleted = 0;
CREATE INDEX IF NOT EXISTS idx_grp_member_request ON grp_member (campus_id, request_id, join_status);

CREATE TABLE IF NOT EXISTS grp_trial (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  request_id BIGINT NOT NULL,
  trial_time TIMESTAMPTZ NOT NULL,
  location VARCHAR(200) NOT NULL,
  teacher_id BIGINT,
  class_id BIGINT,
  wechat_qr_file_id BIGINT,
  status VARCHAR(20) NOT NULL DEFAULT 'ARRANGED',
  arranged_by BIGINT REFERENCES sys_user (id),
  arranged_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  remark VARCHAR(500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_grp_trial_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_grp_trial_request FOREIGN KEY (campus_id, request_id) REFERENCES grp_request (campus_id, id),
  CONSTRAINT fk_grp_trial_teacher FOREIGN KEY (campus_id, teacher_id) REFERENCES edu_teacher (campus_id, id),
  CONSTRAINT fk_grp_trial_class FOREIGN KEY (campus_id, class_id) REFERENCES edu_class (campus_id, id),
  CONSTRAINT fk_grp_trial_qr FOREIGN KEY (campus_id, wechat_qr_file_id) REFERENCES res_file (campus_id, id)
);
COMMENT ON TABLE grp_trial IS '拼班试听安排';
CREATE INDEX IF NOT EXISTS idx_grp_trial_request ON grp_trial (campus_id, request_id, status);

CREATE TABLE IF NOT EXISTS grp_trial_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  trial_id BIGINT NOT NULL,
  member_id BIGINT,
  student_id BIGINT,
  feedback TEXT NOT NULL,
  result VARCHAR(30) NOT NULL DEFAULT 'FOLLOW_UP',
  next_action VARCHAR(255),
  operator_id BIGINT REFERENCES sys_user (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_trial_feedback_trial FOREIGN KEY (campus_id, trial_id) REFERENCES grp_trial (campus_id, id),
  CONSTRAINT fk_trial_feedback_member FOREIGN KEY (campus_id, member_id) REFERENCES grp_member (campus_id, id),
  CONSTRAINT fk_trial_feedback_student FOREIGN KEY (campus_id, student_id) REFERENCES edu_student (campus_id, id)
);
COMMENT ON TABLE grp_trial_feedback IS '试听反馈';
CREATE INDEX IF NOT EXISTS idx_trial_feedback_trial ON grp_trial_feedback (campus_id, trial_id);

CREATE TABLE IF NOT EXISTS sys_notification (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT REFERENCES sys_campus (id),
  receiver_user_id BIGINT REFERENCES sys_user (id),
  receiver_student_id BIGINT,
  biz_type VARCHAR(50) NOT NULL,
  biz_id BIGINT,
  title VARCHAR(150) NOT NULL,
  content TEXT,
  read_at TIMESTAMPTZ,
  status VARCHAR(20) NOT NULL DEFAULT 'UNREAD',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_notification_student FOREIGN KEY (campus_id, receiver_student_id) REFERENCES edu_student (campus_id, id)
);
COMMENT ON TABLE sys_notification IS '站内通知与小程序待办';
CREATE INDEX IF NOT EXISTS idx_notification_receiver ON sys_notification (campus_id, receiver_user_id, status);
CREATE INDEX IF NOT EXISTS idx_notification_student ON sys_notification (campus_id, receiver_student_id, status);

CREATE TABLE IF NOT EXISTS sys_operation_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT REFERENCES sys_campus (id),
  operator_id BIGINT REFERENCES sys_user (id),
  module_name VARCHAR(80) NOT NULL,
  operation_name VARCHAR(80) NOT NULL,
  biz_type VARCHAR(50),
  biz_id BIGINT,
  request_method VARCHAR(16),
  request_uri VARCHAR(255),
  ip VARCHAR(64),
  user_agent VARCHAR(500),
  content JSONB NOT NULL DEFAULT '{}'::JSONB,
  result_status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0
);
COMMENT ON TABLE sys_operation_log IS '敏感操作审计日志';
CREATE INDEX IF NOT EXISTS idx_operation_log_time ON sys_operation_log (campus_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_operation_log_operator ON sys_operation_log (operator_id, created_at DESC);

DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'sys_campus',
    'sys_user',
    'sys_role',
    'sys_permission',
    'sys_role_permission',
    'sys_user_role',
    'sys_user_campus',
    'edu_teacher',
    'edu_course',
    'edu_class',
    'edu_class_teacher',
    'edu_guardian',
    'edu_student',
    'edu_student_guardian',
    'edu_class_student',
    'edu_class_schedule',
    'res_file',
    'res_category',
    'res_material',
    'res_material_class',
    'ops_activity',
    'fin_order',
    'fin_payment_record',
    'ops_activity_registration',
    'edu_lesson_hour_account',
    'edu_lesson_hour_record',
    'edu_attendance',
    'edu_homework',
    'edu_homework_target',
    'edu_homework_attachment',
    'edu_homework_submission',
    'edu_homework_submission_file',
    'edu_homework_comment',
    'edu_homework_checkin',
    'grp_rule',
    'grp_request',
    'grp_member',
    'grp_trial',
    'grp_trial_feedback',
    'sys_notification',
    'sys_operation_log'
  ]
  LOOP
    EXECUTE FORMAT('DROP TRIGGER IF EXISTS trg_set_updated_at ON %I', table_name);
    EXECUTE FORMAT(
      'CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at()',
      table_name
    );
  END LOOP;
END;
$$;
