ALTER TABLE edu_course
  ADD COLUMN IF NOT EXISTS public_summary VARCHAR(255),
  ADD COLUMN IF NOT EXISTS public_detail TEXT,
  ADD COLUMN IF NOT EXISTS cover_file_id BIGINT,
  ADD COLUMN IF NOT EXISTS public_status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
  ADD COLUMN IF NOT EXISTS display_order INTEGER NOT NULL DEFAULT 0;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_edu_course_cover_file'
  ) THEN
    ALTER TABLE edu_course
      ADD CONSTRAINT fk_edu_course_cover_file
      FOREIGN KEY (campus_id, cover_file_id) REFERENCES res_file (campus_id, id);
  END IF;
END;
$$;

ALTER TABLE edu_teacher
  ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(512);

CREATE TABLE IF NOT EXISTS edu_course_teacher (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  course_id BIGINT NOT NULL,
  teacher_id BIGINT NOT NULL,
  role_name VARCHAR(50),
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_edu_course_teacher_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_course_teacher_course FOREIGN KEY (campus_id, course_id) REFERENCES edu_course (campus_id, id),
  CONSTRAINT fk_course_teacher_teacher FOREIGN KEY (campus_id, teacher_id) REFERENCES edu_teacher (campus_id, id)
);
COMMENT ON TABLE edu_course_teacher IS 'Public course teacher display relation';
CREATE UNIQUE INDEX IF NOT EXISTS uk_course_teacher_alive
  ON edu_course_teacher (campus_id, course_id, teacher_id) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS edu_course_registration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id BIGINT NOT NULL REFERENCES sys_campus (id),
  course_id BIGINT NOT NULL,
  student_id BIGINT,
  guardian_id BIGINT NOT NULL,
  order_id BIGINT,
  preferred_class_id BIGINT,
  assigned_class_id BIGINT,
  registration_no VARCHAR(40) NOT NULL,
  applicant_name VARCHAR(50),
  applicant_phone VARCHAR(20) NOT NULL,
  child_name VARCHAR(50) NOT NULL,
  child_age NUMERIC(4, 1),
  child_grade VARCHAR(30),
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'WAITING_PAY',
  note VARCHAR(500),
  review_remark VARCHAR(500),
  registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  paid_at TIMESTAMPTZ,
  reviewed_at TIMESTAMPTZ,
  confirmed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT,
  updated_by BIGINT,
  deleted SMALLINT NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uk_course_registration_campus_id_id UNIQUE (campus_id, id),
  CONSTRAINT fk_course_registration_course FOREIGN KEY (campus_id, course_id) REFERENCES edu_course (campus_id, id),
  CONSTRAINT fk_course_registration_student FOREIGN KEY (campus_id, student_id) REFERENCES edu_student (campus_id, id),
  CONSTRAINT fk_course_registration_guardian FOREIGN KEY (campus_id, guardian_id) REFERENCES edu_guardian (campus_id, id),
  CONSTRAINT fk_course_registration_order FOREIGN KEY (campus_id, order_id) REFERENCES fin_order (campus_id, id),
  CONSTRAINT fk_course_registration_preferred_class FOREIGN KEY (campus_id, preferred_class_id) REFERENCES edu_class (campus_id, id),
  CONSTRAINT fk_course_registration_assigned_class FOREIGN KEY (campus_id, assigned_class_id) REFERENCES edu_class (campus_id, id)
);
COMMENT ON TABLE edu_course_registration IS 'Course registration and admission workflow';
CREATE UNIQUE INDEX IF NOT EXISTS uk_course_registration_no_alive
  ON edu_course_registration (registration_no) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_course_registration_status
  ON edu_course_registration (campus_id, status, registered_at DESC);
CREATE INDEX IF NOT EXISTS idx_course_registration_guardian
  ON edu_course_registration (campus_id, guardian_id, registered_at DESC);

INSERT INTO sys_permission (
  id, parent_id, code, name, permission_type, route_path, component, api_method, api_path, icon, sort_order, status, created_by, updated_by
)
SELECT 115,
       (SELECT id FROM sys_permission WHERE code = 'operation' AND deleted = 0 LIMIT 1),
       'operation:admission', '招生管理', 'MENU', '/admissions', 'operation/AdmissionCenter',
       NULL, NULL, 'clipboard-list', 25, 'ENABLED', 1, 1
WHERE NOT EXISTS (
  SELECT 1 FROM sys_permission WHERE code = 'operation:admission' AND deleted = 0
);

INSERT INTO sys_role_permission (role_id, permission_id, created_by, updated_by)
SELECT r.id, p.id, 1, 1
FROM sys_role r
JOIN sys_permission p ON p.code = 'operation:admission' AND p.deleted = 0
WHERE r.code IN ('SUPER_ADMIN', 'CAMPUS_ADMIN')
  AND r.deleted = 0
  AND NOT EXISTS (
      SELECT 1
      FROM sys_role_permission existing
      WHERE existing.role_id = r.id
        AND existing.permission_id = p.id
        AND existing.deleted = 0
  );

DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'edu_course_teacher',
    'edu_course_registration'
  ]
  LOOP
    EXECUTE FORMAT('DROP TRIGGER IF EXISTS trg_set_updated_at ON %I', table_name);
    EXECUTE FORMAT(
      'CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at()',
      table_name
    );
  END LOOP;
END;
$$;
